language: python
python:
- '3.6'
install:
- pip install -r dev-requirements.txt
- cd python
- pip install .
script:
- pytest ./test/example_tests/*
deploy:
  provider: pypi
  user: __token__
  password:
    secure: SyAd4KYdOPYDcG1DI4y1RHgyI/ktam4PvJWrjanu20KrB5CQU8T4fnjslD+h2igatzNvu7lt2g3jIaah45q3HZd7WMSUJTu0F8NgVfzFOQC77ivnOOEMR6iZooqTKPLPqJ96qwPwHqDpZbPz2iKDyLCkC+oA4gAGq7LInOYmC4kwaKwU8WyakB1AyoZyfXwtdjwsQE6gCdZOJXgjAGSFvKkxnd79V57/QR8YqIVVV5GnnMYLPRfCq9dzZni0nWpSTqjQ38d3/8moxw9pacPE5Nx2hM9EYxoa/Rr84ULijSHOvZZ30paFt5omKBvA1X1F+9BXVIsPFnv++ytAce8nMV+MXpmt3yFOaXtvIl6tpus7OKytjoaEq3Xg+rcwLgJLHCpnIgflOZXOviY8GgL6PDohTWt5/mttrnsHwJ03PZOUah2Y0F10FrxJ7LhowfGZ2LIkjDbEY7T85jyl7gef9Q7oQCQeboDsJjkmFkWNvdYt40yG+sHUaPYfU/5TyqEPYId2kICa8qD3UaA9v4RANmIsD4hrIF8F8PjYX4xCSNTf5+cFB2l9lsK25fSA9Jx8xkXdyPWwwWjEwpQ16QINme51PmgxNuWU2rFQwMEPX0y++3y38KflBNP3fbGUYWVci03DZ3CZusmqTKOHzA4PR8Eg5s8QrUQoZPYwaQHhTAc=
