language: python
python:
- '3.6'
install:
- pip install -r dev-requirements.txt
- cd python
- pip install .
script:
- pytest ./test/example_tests/*
deploy:
  provider: pypi
  user: __token__
  password:
    secure: r9a8UtuyH4jQ0Lv4hoJs77X3n5rq+YhSO2T+c4MgaKl4SbVW5K4TNLHx/TDOoWeUKHDqtBcjnLzoHAEKQixobXKLpjel948QDOJTA3+j1p1A/phzozx8phlxuk8JtSV8B9aPBhnloXMw0ZCCFm24nJOTvEovcZpsYRac1WQJWGahUbHZUIS1hdg8tO3ESMmaMBSZvGkOjXSBKNUAsjdH2fp6xdz2J7C5IhFCuudOIxpuFvxGfZd4wE1pWuqoY8a4ubv2k5qc5lbJnB5nyZfPR+gLE0aX0NnfLs7bRaSvK5xVp9tWhS5AX4BNBuzGPOL9Q5N1WFN0B1vQAx1RTC+q/mfa/Fl3a6rGaE4zf3O+WBYzp0szZhMTZn3ni6WLb8dk/fq2fEftTsDWNaWDstrI5sAw0p1I0rO2ujOjvc35HSYdCSgmI8hZChJNXACGvORWeMIdHtt6tSygdNzE7oZ1pi+si07NfwzAHOqL9ZWd+BavFjEDMPs2L4MLjc0P7iJwSiFB218ITtmVcK4rlju5ADiYE6VkbM9W9FUh25o2eUl8diAsyMrL3v/xH11FwlTL8gRn6DeZhxB6sqvL8nh0fNA0XfKeQtsLdqEkgLPNpmeAWTGctJ/qv/muwV1nEUi4gzliVSQBXV5Q4+N8owBJJTDDiyiJ2gbXsIe8FHzmHgI=
